### PR TITLE
Fallback to GPU when trying to render with CPU with HybridPro

### PR DESCRIPTION
**Pull request by Licoman256**
JIRA TICKET: RPRMAYA-3229

PURPOSE: HybridPro does not support rendering with CPU. This PR allows the user to select only GPU when HybridPro is chosen. CPU option is grayed out

EFFECT FOR THE USER: HybridPro renders using GPU. CPU option is grayed out. Unknown error no longer occurs when trying to render with CPU.

### CODE REVIEW

**Comment by DavidSpeicher** [comment]
QA Approved

**Review by DMotorygin — APPROVED** [review]

**Comment by bsavery** [comment]
Shouldn't we grey out the CPU option?

**Comment by Licoman256** [comment]
> Shouldn't we grey out the CPU option?

What should we do if the user chooses CPU with NorthStar enabled, then changes NorthStar to HybridPro? Should we display a message asking the user to change the setting? We could also give a notification and change it ourselves. What kind of notification/error should we give? A popup or in script editor?

**Comment by bsavery** [comment]
Just grey it out and leave the setting and ignore.  Does that work?

**Pull request merged**
